name: scan build container

on:
  workflow_run:
    workflows: [build_and_publish_container]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dockerhub

    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ vars.DOCKER_HUB_ORGANIZATION }}/${{ vars.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          security-checks: 'vuln'
          severity: 'CRITICAL,HIGH'
          timeout: '30m'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'